#!/bin/bash
source ../common/functions.sh
source ../common/mpiruns.sh
source ../common/ompruns.sh
source ../common/runs.sh

bentype="$1"
benchmark="$2"
benchs="$3"
class="$4"
nprocs=$5
bendir="$6"
runlog="/tmp/runlog.txt"
rep=$7
extra=$(hostname)
email="3090104738@zju.edu.cn"

for i in $(seq 1 $rep); do
    $benchmark "$benchs" $class $nprocs "$bendir" "$runlog" $bentype
    echo "$benchmark \"$benchs\" $class $nprocs \"$bendir\" \"$runlog\" $bentype"
    show_run_info "$benchs" $class $nprocs $benchmark >> "$runlog"
    after_run $bentype "$bendir" $extra "$runlog" $benchmark $email
done
rm "$runlog"
