#!/usr/bin/env ruby
require '../common/npb'

def genTable(ben_type, dir, benchs, cls, nprocs, names)
    info = NPB::parseTable ben_type, dir, benchs, cls, nprocs, names, 'bind-socket' 
    names.each do |name|
        puts name
        benchs.each do |bench1|
            print "#{bench1}: "
            benchs.each do |bench2|
                printf "%8.7s ", info["#{bench1}-#{bench2}"][name]
            end
            puts ''
        end
    end
end

if __FILE__ == $0
    if ARGV.size != 1
        puts "Generate result table for dual runs."
        puts "Usage:\n#{$0} dir"
        exit
    end
    genTable 'mpi', ARGV[0], NPB::MPI_BENCHS,
        'A', 1, NPB::NORMAL_NAME
end
